<?php

require_once dirname(__FILE__) . '/../../Models/User.php';

/**
 * Test class for User.
 * Generated by PHPUnit on 2012-06-07 at 11:41:27.
 */
class UserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new User(0);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testFields()
    {
        
        $this->assertSame('danb', $this->object->username);
        echo $this->object->password . "\n";
        
    }
    
    public function testCommitToDB()
    {
        
        
        $this->object->username = 'danb';
        
        $this->object->password = 'tldstok';
        
        echo $this->object->password;
        
        
        
        
       
        $this->object->commitToDB();
        
      
    }

}

?>
